function coeffs = CoefSMAC(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COEFLANDSAT1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  COEFLANDSAT1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  CoefLANDSAT1 = importfile("F:\camryn\SL2PD-master\DATA\smac-python-971e2e77fd9e5b94e39a5bc9417cc000f5984a98\smac-python.git\COEFS\Coef_LANDSAT8_440_1.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Jul-2020 16:45:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts = setvaropts(opts, 4, "TrimNonNumeric", true);
opts = setvaropts(opts, 4, "ThousandsSeparator", ",");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
%% Convert to output type
a = reshape(table2array( readtable(filename, opts))',[],1);
coeffs = a(~isnan(a));
end