function srf = Sentinel2Asrf(workbookFile, sheetName,  band)
%IMPORTFILE Import data from a spreadsheet
%  srf = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  srf = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  srf = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  BallBARSRS1 = importfile("F:\camryn\SL2PD-master\DATA\spectral-response-functions\Ball_BA_RSR.v1.2.xlsx", "Spectral Responses (S2A)", [2, 2302]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Jul-2020 17:24:16

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end


    dataLines = [2, 2302];


%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":N" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["SR_WL", "S2A_SR_AV_B1", "S2A_SR_AV_B2", "S2A_SR_AV_B3", "S2A_SR_AV_B4", "S2A_SR_AV_B5", "S2A_SR_AV_B6", "S2A_SR_AV_B7", "S2A_SR_AV_B8", "S2A_SR_AV_B8A", "S2A_SR_AV_B9", "S2A_SR_AV_B10", "S2A_SR_AV_B11", "S2A_SR_AV_B12"];
opts.SelectedVariableNames = ["SR_WL", "S2A_SR_AV_B1", "S2A_SR_AV_B2", "S2A_SR_AV_B3", "S2A_SR_AV_B4", "S2A_SR_AV_B5", "S2A_SR_AV_B6", "S2A_SR_AV_B7", "S2A_SR_AV_B8", "S2A_SR_AV_B8A", "S2A_SR_AV_B9", "S2A_SR_AV_B10", "S2A_SR_AV_B11", "S2A_SR_AV_B12"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
data = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":N" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    data = [data; tb]; %#ok<AGROW>
end

response = data.(['S2A_SR_AV_',band]);
srf.lambda  = data.SR_WL(find(response>0, 1,'first'):find(response>0, 1,'last'));
srf.sensi = response(find(response>0, 1,'first'):find(response>0, 1,'last'));
srf.begin_mode_end = [min(srf.lambda),srf.lambda(find(srf.sensi==max(srf.sensi),1,'first')) max(srf.lambda)];


end